name: mike
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34061
title: Mike Lerner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090b0a'
    - '#474538'
    - '#81865b'
    - '#abb070'
    - '#ebd4c5'
  brandStrength: 0.21501444815658033
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
