name: mike
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34061
title: Mike Lerner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21501444815658033
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
