name: mike
favicon: null
layout_spectrum: 0.6386355240829289
typography_spectrum: 0.8562973241787404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21501444815658033
  lightness: 0.145671529462561
  saturation: 0.7124576594214886
  rhythmicContrast: 0.605106224771589
purpose: []
